# Generated by Django 4.1.7 on 2023-03-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('studentAssignment', models.CharField(max_length=100)),
                ('studentFilePath', models.CharField(max_length=200)),
            ],
        ),
    ]
