# Generated by Django 4.1.7 on 2023-03-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackAssignment', models.CharField(max_length=200)),
                ('submissionId', models.IntegerField()),
                ('studentId', models.IntegerField()),
                ('assignmentName', models.CharField(max_length=200)),
            ],
        ),
    ]
